### PR TITLE
Added methods for next tab, previous tab, getting the tab-index, and activating by tab index.

### PR DESCRIPTION
**Pull request by dsandber**

### CODE REVIEW

**Comment by freekmurze** [comment]
Please add tests ro prove that this works

**Comment by dsandber** [comment]
Hi Freek, will do, but it'll take me two weeks or so to get to it.  Just returned from a business trip abroad and have a lot to catch-up with at home.

**Comment by freekmurze** [comment]
Closing due to inactivity.

**Comment by dsandber** [comment]
I made a new pull request with regression tests:

https://github.com/spatie/vue-tabs-component/pull/24

**Comment by freekmurze** [comment]
We'll handle this further in #24

**Pull request closed without merging**
