### PR TITLE
Add comfortable utility methods to Tabs component

### PR DESCRIPTION
**Pull request by matewiszt**
Add getTabIndex, getTabHash, getActiveTab and getActiveTabIndex methods to Tabs component.

### CODE REVIEW

**Comment by matewiszt** [comment]
Some utility methods to make the tab management easier.

**Comment by matewiszt** [comment]
Add activeTabIndex to Tabs

**Comment by matewiszt** [comment]
Do you intend to merge my modifications into the project? May I get feedback from you?

**Comment by ScreamZ** [comment]
+1 @sebastiandedeyne

**Comment by sebastiandedeyne** [comment]
Thanks!

**Pull request merged**
