### PR TITLE
Add nextTab & previousTab methods

### PR DESCRIPTION
**Pull request by dsandber**
This change is [Reviewable](https://reviewable.io/reviews/spatie/vue-tabs-component/77)

### CODE REVIEW

**Comment by dsandber** [comment]
I tried to include all the feedback from:

https://github.com/spatie/vue-tabs-component/pull/24#pullrequestreview-69463709

I wasn't sure what was intended in terms of the suggestion to use "const" in nextTab and previousTab.

I could imagine accomplishing the same thing with the modulo operator (%) and some ternary operators so that "const" could be used, but it would make the code less readable.  I'm open to suggestions though.

**Comment by dsandber** [comment]
Anyone home?

**Comment by christian-kolb** [comment]
I was searching for exactly this functionality. Is it possible to merge this pull request? 🙂

**Comment by dsandber** [comment]
Perhaps use my branch until this gets merged?

**Comment by freekmurze** [comment]
We don't use this package anymore in our own projects and cannot justify the time needed to maintain it anymore. That's why we have chosen to abandon it. Feel free to fork our code and maintain your own copy.

**Pull request closed without merging**
